Repository among-neighbors/AN-backend, pull requests merged in 2022-09, with the labels that each got.

#105 Feat: Notice 수정, 삭제 기능 추가
  src/main/java/com/knud4/an/config/SecurityConfig.java
  src/main/java/com/knud4/an/notice/controller/NoticeController.java
  src/main/java/com/knud4/an/notice/entity/Notice.java
  src/main/java/com/knud4/an/notice/repository/NoticeRepository.java
  src/main/java/com/knud4/an/notice/service/NoticeService.java
Labels: documentation, enhancement

#111 Feat: Comment api response 데이터 수정
  src/main/java/com/knud4/an/comment/controller/CommentController.java
  src/main/java/com/knud4/an/comment/dto/CommentDTO.java
  src/main/java/com/knud4/an/comment/dto/CommentListDTO.java
  src/main/java/com/knud4/an/comment/service/CommunityCommentService.java
  src/main/java/com/knud4/an/comment/service/ReportCommentService.java
Labels: documentation, enhancement

#113 Refactor: security 및 권한 확인, api url 정리
  src/main/java/com/knud4/an/auth/controller/AuthController.java
  src/main/java/com/knud4/an/comment/controller/CommentController.java
  src/main/java/com/knud4/an/community/controller/CommunityController.java
  src/main/java/com/knud4/an/community/service/CommunityService.java
  src/main/java/com/knud4/an/config/SecurityConfig.java
  src/main/java/com/knud4/an/config/WebConfig.java
  src/main/java/com/knud4/an/interceptor/AccountRequired.java
  src/main/java/com/knud4/an/interceptor/AccountTokenInterceptor.java
  src/main/java/com/knud4/an/interceptor/ProfileRequired.java
  src/main/java/com/knud4/an/interceptor/ProfileTokenInterceptor.java
  src/main/java/com/knud4/an/notice/controller/NoticeController.java
  src/main/java/com/knud4/an/notice/service/NoticeService.java
  src/main/java/com/knud4/an/report/controller/ReportController.java
Labels: documentation

#109 Feat: 1:1 Messaging Queue 추가, 비상 알림 수락 추가
  src/main/java/com/knud4/an/config/StompWebSocketConfig.java
  src/main/java/com/knud4/an/exception/IllegalMessagingException.java
  src/main/java/com/knud4/an/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/knud4/an/websocket/controller/AlertController.java
  src/main/java/com/knud4/an/websocket/dto/AcceptDTO.java
  src/main/java/com/knud4/an/websocket/interceptor/StompInboundInterceptor.java
Labels: documentation, enhancement

#115 Fix: JwtProfile Filter 에 profile 검증 로직 추가
  src/main/java/com/knud4/an/security/details/ProfileDetailsService.java
  src/main/java/com/knud4/an/security/filter/JwtProfileAuthenticationFilter.java
  src/main/java/com/knud4/an/security/provider/JwtProvider.java
Labels: bug

#114 Refactor: Report List 응답 로직 수정
  src/main/java/com/knud4/an/report/controller/ReportController.java
  src/main/java/com/knud4/an/report/dto/ReportDTO.java
  src/main/java/com/knud4/an/report/dto/ReportListDTO.java
  src/main/java/com/knud4/an/report/repository/ReportRepository.java
  src/main/java/com/knud4/an/report/service/ReportService.java
Labels: documentation, enhancement

#117 Refactor: annotation package 정리, Profile 응답 로직 수정
  src/main/java/com/knud4/an/account/controller/AccountController.java
  src/main/java/com/knud4/an/account/dto/ProfileDTO.java
  src/main/java/com/knud4/an/account/dto/ProfileListResponse.java
  src/main/java/com/knud4/an/annotation/AccountRequired.java
  src/main/java/com/knud4/an/annotation/ProfileRequired.java
  src/main/java/com/knud4/an/auth/controller/AuthController.java
  src/main/java/com/knud4/an/comment/controller/CommentController.java
  src/main/java/com/knud4/an/community/controller/CommunityController.java
  src/main/java/com/knud4/an/interceptor/AccountTokenInterceptor.java
  src/main/java/com/knud4/an/interceptor/ProfileTokenInterceptor.java
  src/main/java/com/knud4/an/notice/controller/NoticeController.java
  src/main/java/com/knud4/an/report/controller/ReportController.java
Labels: documentation

#119 Refactor: 민원 조회 응답 데이터에 Writer id 추가
  src/main/java/com/knud4/an/account/controller/AccountController.java
  src/main/java/com/knud4/an/account/dto/ProfileDTO.java
  src/main/java/com/knud4/an/account/dto/ProfileListResponse.java
  src/main/java/com/knud4/an/account/entity/Account.java
  src/main/java/com/knud4/an/account/entity/Profile.java
  src/main/java/com/knud4/an/report/dto/ReportDTO.java
Labels: documentation

#122 Feat: Manager Login 추가
  src/main/java/com/knud4/an/auth/controller/AuthController.java
  src/main/java/com/knud4/an/auth/dto/manager/SignInManagerResponse.java
  src/main/java/com/knud4/an/auth/service/AuthService.java
Labels: documentation

#123 Refactor: Account Entity 에서 line, house 정보 저장
  src/main/java/com/knud4/an/account/controller/AccountController.java
  src/main/java/com/knud4/an/account/dto/ProfileDTO.java
  src/main/java/com/knud4/an/account/entity/Account.java
Labels: documentation

#124 Feat: Community, Notice, Comment 응답 로직 수정
  src/main/java/com/knud4/an/board/Board.java
  src/main/java/com/knud4/an/board/Scope.java
  src/main/java/com/knud4/an/comment/repository/CommunityCommentRepository.java
  src/main/java/com/knud4/an/comment/repository/ReportCommentRepository.java
  src/main/java/com/knud4/an/community/controller/CommunityController.java
  src/main/java/com/knud4/an/community/dto/CommunityDTO.java
  src/main/java/com/knud4/an/community/dto/CreateCommunityForm.java
  src/main/java/com/knud4/an/community/entity/Community.java
  src/main/java/com/knud4/an/community/repository/CommunityRepository.java
  src/main/java/com/knud4/an/community/service/CommunityService.java
  src/main/java/com/knud4/an/notice/controller/NoticeController.java
  src/main/java/com/knud4/an/notice/dto/CreateNoticeForm.java
  src/main/java/com/knud4/an/notice/dto/NoticeDTO.java
  src/main/java/com/knud4/an/notice/entity/Notice.java
  src/main/java/com/knud4/an/notice/repository/NoticeRepository.java
  src/main/java/com/knud4/an/notice/service/NoticeService.java
Labels: documentation, fix

#125 Fix: Community, Notice, Comment isLastPage, isFirstPage 오류 수정
  src/main/java/com/knud4/an/comment/service/CommunityCommentService.java
  src/main/java/com/knud4/an/comment/service/ReportCommentService.java
  src/main/java/com/knud4/an/community/service/CommunityService.java
  src/main/java/com/knud4/an/notice/service/NoticeService.java
Labels: fix

#126 Feat: Community 오류 수정 및 Comment 응답 로직 수정
  src/main/java/com/knud4/an/comment/controller/CommentController.java
  src/main/java/com/knud4/an/comment/dto/CommentDTO.java
  src/main/java/com/knud4/an/community/service/CommunityService.java
Labels: enhancement, fix

#130 Fix: 모든 게시글 상세 조회 관리자 접근 권한 추가
  src/main/java/com/knud4/an/community/service/CommunityService.java
  src/main/java/com/knud4/an/notice/service/NoticeService.java
  src/main/java/com/knud4/an/report/service/ReportService.java
Labels: fix

#132 Feat: Comment 응답 로직에 writerId 추가
  src/main/java/com/knud4/an/comment/dto/CommentDTO.java
Labels: documentation

#133 Fix: security 관리자 프로필 권한 추가
  src/main/java/com/knud4/an/config/SecurityConfig.java
Labels: fix

#137 Feat: Jwt 관련 예외 핸들링 필터 추가
  src/main/java/com/knud4/an/config/SecurityConfig.java
  src/main/java/com/knud4/an/exception/TokenNotFoundException.java
  src/main/java/com/knud4/an/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/knud4/an/security/filter/JwtExceptionFilter.java
  src/main/java/com/knud4/an/security/filter/JwtProfileAuthenticationFilter.java
  src/main/java/com/knud4/an/utils/jwt/JwtExtractor.java
Labels: documentation, enhancement

#139 Refactor: Jwt Header Parsing Interceptor 삭제
  src/main/java/com/knud4/an/config/WebConfig.java
  src/main/java/com/knud4/an/interceptor/ProfileTokenInterceptor.java
  src/main/java/com/knud4/an/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/knud4/an/security/filter/JwtProfileAuthenticationFilter.java
Labels: documentation

#128 Feat: Swagger 정보 추가
  src/main/java/com/knud4/an/account/controller/AccountController.java
  src/main/java/com/knud4/an/auth/controller/AuthController.java
  src/main/java/com/knud4/an/comment/controller/CommentController.java
  src/main/java/com/knud4/an/comment/service/ReportCommentService.java
  src/main/java/com/knud4/an/community/controller/CommunityController.java
  src/main/java/com/knud4/an/community/service/CommunityService.java
  src/main/java/com/knud4/an/house/controller/HouseController.java
  src/main/java/com/knud4/an/line/controller/LineController.java
  src/main/java/com/knud4/an/notice/controller/NoticeController.java
  src/main/java/com/knud4/an/notice/service/NoticeService.java
  src/main/java/com/knud4/an/report/controller/ReportController.java
  src/main/java/com/knud4/an/report/repository/ReportRepository.java
  src/main/java/com/knud4/an/report/service/ReportService.java
  src/main/java/com/knud4/an/smtp/controller/AuthMailController.java
Labels: documentation

#143 Fix: Community, Notice 목록 조회 로직 변경
  src/main/java/com/knud4/an/account/repository/AccountRepository.java
  src/main/java/com/knud4/an/account/service/AccountService.java
  src/main/java/com/knud4/an/community/controller/CommunityController.java
  src/main/java/com/knud4/an/community/repository/CommunityRepository.java
  src/main/java/com/knud4/an/community/service/CommunityService.java
  src/main/java/com/knud4/an/notice/controller/NoticeController.java
  src/main/java/com/knud4/an/notice/repository/NoticeRepository.java
  src/main/java/com/knud4/an/notice/service/NoticeService.java
  src/main/java/com/knud4/an/report/service/ReportService.java
  src/main/java/com/knud4/an/security/details/ProfileDetailsService.java
  src/main/java/com/knud4/an/websocket/interceptor/StompInboundInterceptor.java
Labels: fix

#142 Refactor: 로깅 로직 수정
  src/main/java/com/knud4/an/exception/CookieNotFoundException.java
  src/main/java/com/knud4/an/logger/LoggingFilter.java
  src/main/java/com/knud4/an/security/filter/JwtExceptionFilter.java
  src/main/java/com/knud4/an/utils/cookie/CookieUtil.java
Labels: documentation

#144 Fix: Community, Report, Notice 목록 오류 수정
  src/main/java/com/knud4/an/account/entity/Account.java
  src/main/java/com/knud4/an/account/entity/Profile.java
  src/main/java/com/knud4/an/base/BaseEntity.java
  src/main/java/com/knud4/an/base/BaseTimeEntity.java
  src/main/java/com/knud4/an/board/Board.java
  src/main/java/com/knud4/an/comment/entity/Comment.java
  src/main/java/com/knud4/an/community/controller/CommunityController.java
  src/main/java/com/knud4/an/community/repository/CommunityRepository.java
  src/main/java/com/knud4/an/community/service/CommunityService.java
  src/main/java/com/knud4/an/line/entity/Line.java
  src/main/java/com/knud4/an/notice/controller/NoticeController.java
  src/main/java/com/knud4/an/notice/repository/NoticeRepository.java
  src/main/java/com/knud4/an/notice/service/NoticeService.java
  src/main/java/com/knud4/an/report/controller/ReportController.java
  src/main/java/com/knud4/an/report/entity/Report.java
  src/main/java/com/knud4/an/report/repository/ReportRepository.java
  src/main/java/com/knud4/an/report/service/ReportService.java
Labels: fix

#146 README 추가
  README.md
Labels: documentation

#148 Access Token 캐싱, 로깅 제외 항목 추가
  src/main/java/com/knud4/an/auth/controller/AuthController.java
  src/main/java/com/knud4/an/config/WebConfig.java
  src/main/java/com/knud4/an/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/knud4/an/logger/LoggingFilter.java
  src/main/java/com/knud4/an/security/provider/JwtProvider.java
  src/test/java/com/knud4/an/AnApplicationTests.java
  src/test/java/com/knud4/an/repository/AccountRepositoryTest.java
  src/test/java/com/knud4/an/repository/HouseRepositoryTest.java
  src/test/java/com/knud4/an/repository/LineRepositoryTest.java
  src/test/java/com/knud4/an/service/AccountServiceTest.java
  src/test/java/com/knud4/an/service/LineServiceTest.java
Labels: documentation, enhancement

#150 Refactor: 메세징 예외 분리, 메세징 반환 헤더에 메세지 타입 포함
  src/main/java/com/knud4/an/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/knud4/an/exception/websocket/IllegalMessagingException.java
  src/main/java/com/knud4/an/websocket/controller/AlertController.java
  src/main/java/com/knud4/an/websocket/interceptor/StompInboundInterceptor.java
Labels: documentation

#152 Feat: Password Validator
  src/main/java/com/knud4/an/auth/service/AuthService.java
Labels: documentation, enhancement

#153 v1.1 배포
  src/main/java/com/knud4/an/auth/controller/AuthController.java
  src/main/java/com/knud4/an/auth/service/AuthService.java
  src/main/java/com/knud4/an/config/WebConfig.java
  src/main/java/com/knud4/an/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/knud4/an/exception/websocket/IllegalMessagingException.java
  src/main/java/com/knud4/an/logger/LoggingFilter.java
  src/main/java/com/knud4/an/security/provider/JwtProvider.java
  src/main/java/com/knud4/an/websocket/controller/AlertController.java
  src/main/java/com/knud4/an/websocket/interceptor/StompInboundInterceptor.java
  src/test/java/com/knud4/an/AnApplicationTests.java
  src/test/java/com/knud4/an/repository/AccountRepositoryTest.java
  src/test/java/com/knud4/an/repository/HouseRepositoryTest.java
  src/test/java/com/knud4/an/repository/LineRepositoryTest.java
  src/test/java/com/knud4/an/service/AccountServiceTest.java
  src/test/java/com/knud4/an/service/LineServiceTest.java
Labels: enhancement, release

#159 오픈소스 파일 재 추가
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENSE
  README.md
Labels: documentation

#160 오픈소스 파일 재 추가
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENSE
  README.md
Labels: documentation
