Repository among-neighbors/AN-backend, pull requests merged in 2022-08, with the labels that each got.

#13 Feat: JWT Util Class 추가
  src/main/java/com/knud4/an/utils/jwt/JWTUtil.java
Labels: documentation, enhancement

#17 Feat: Cookie Util Class 추가
  src/main/java/com/knud4/an/utils/cookie/CookieUtil.java
Labels: documentation, enhancement

#18 Feat: Account, Profile Entity, Account Repository 추가
  src/main/java/com/knud4/an/account/entity/Account.java
  src/main/java/com/knud4/an/account/entity/Gender.java
  src/main/java/com/knud4/an/account/entity/Profile.java
  src/main/java/com/knud4/an/account/entity/Role.java
  src/main/java/com/knud4/an/account/repository/AccountRepository.java
  src/test/java/com/knud4/an/repository/AccountRepositoryTest.java
Labels: documentation, enhancement

#21 Feat: House Id 조회 추가, Service 조회 값 수정
  src/main/java/com/knud4/an/house/dto/CreateHouseForm.java
  src/main/java/com/knud4/an/house/entity/House.java
  src/main/java/com/knud4/an/house/repository/HouseRepository.java
  src/main/java/com/knud4/an/house/service/HouseService.java
  src/test/java/com/knud4/an/repository/AccountRepositoryTest.java
  src/test/java/com/knud4/an/repository/HouseRepositoryTest.java
Labels: documentation, enhancement

#23 Feat: AccountService 추가
  src/main/java/com/knud4/an/account/service/AccountService.java
  src/test/java/com/knud4/an/service/LineServiceTest.java
Labels: documentation, enhancement

#26 Feat: spring security 추가 및 추가에 따른 기존 클래스 일부 수정
  build.gradle
  src/main/java/com/knud4/an/account/entity/Account.java
  src/main/java/com/knud4/an/config/SecurityConfigure.java
  src/main/java/com/knud4/an/security/details/AccountDetails.java
  src/main/java/com/knud4/an/security/details/AccountDetailsService.java
  src/main/java/com/knud4/an/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/knud4/an/security/provider/JwtProvider.java
Labels: documentation, enhancement

#24 Feat: AuthService 추가
  src/main/java/com/knud4/an/account/entity/Gender.java
  src/main/java/com/knud4/an/account/repository/AccountRepository.java
  src/main/java/com/knud4/an/account/service/AccountService.java
  src/main/java/com/knud4/an/auth/dto/account/SignInAccountForm.java
  src/main/java/com/knud4/an/auth/dto/account/SignInAccountResponse.java
  src/main/java/com/knud4/an/auth/dto/account/SignUpAccountForm.java
  src/main/java/com/knud4/an/auth/dto/account/SignUpAccountResponse.java
  src/main/java/com/knud4/an/auth/dto/profile/AddProfileForm.java
  src/main/java/com/knud4/an/auth/dto/profile/AddProfileResponse.java
  src/main/java/com/knud4/an/auth/dto/profile/SignInProfileForm.java
  src/main/java/com/knud4/an/auth/dto/profile/SignInProfileResponse.java
  src/main/java/com/knud4/an/auth/service/AuthService.java
  src/main/java/com/knud4/an/exception/GlobalExceptionHandler.java
  src/main/java/com/knud4/an/exception/NotAuthenticatedException.java
  src/main/java/com/knud4/an/exception/NotFoundException.java
  src/main/java/com/knud4/an/house/service/HouseService.java
  src/main/java/com/knud4/an/line/service/LineService.java
  src/main/java/com/knud4/an/utils/api/ApiUtil.java
  src/test/java/com/knud4/an/repository/AccountRepositoryTest.java
  src/test/java/com/knud4/an/repository/HouseRepositoryTest.java
  src/test/java/com/knud4/an/repository/LineRepositoryTest.java
Labels: documentation, enhancement

#29 Feat/issue 3/comment entity
  src/main/java/com/knud4/an/comment/entity/Comment.java
  src/main/java/com/knud4/an/comment/repository/CommentRepository.java
Labels: documentation, enhancement

#30 Feat: Notice Entity 추가
  src/main/java/com/knud4/an/notice/entity/Notice.java
  src/main/java/com/knud4/an/notice/repository/NoticeRepository.java
Labels: documentation, enhancement

#32 Account 검증 로직 일부 수정 및 Auth Controller 추가
  src/main/java/com/knud4/an/account/repository/AccountRepository.java
  src/main/java/com/knud4/an/auth/controller/AuthController.java
  src/main/java/com/knud4/an/auth/dto/profile/AddProfileForm.java
  src/main/java/com/knud4/an/auth/dto/profile/SignInProfileForm.java
  src/main/java/com/knud4/an/auth/service/AuthService.java
  src/main/java/com/knud4/an/exception/GlobalExceptionHandler.java
  src/main/java/com/knud4/an/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/knud4/an/security/provider/JwtProvider.java
Labels: documentation, enhancement

#38 Refactor: 라인, 세대명 중복 검증 로직 추가
  src/main/java/com/knud4/an/house/repository/HouseRepository.java
  src/main/java/com/knud4/an/house/service/HouseService.java
  src/main/java/com/knud4/an/line/repository/LineRepository.java
  src/main/java/com/knud4/an/line/service/LineService.java
Labels: documentation

#39 Feat: HouseController 및 DTO 추가
  src/main/java/com/knud4/an/house/controller/HouseController.java
  src/main/java/com/knud4/an/house/dto/HouseDTO.java
  src/main/java/com/knud4/an/house/dto/HouseListResponse.java
Labels: documentation, enhancement

#40 Feat: LineController 및 DTO 추가
  src/main/java/com/knud4/an/line/controller/LineController.java
  src/main/java/com/knud4/an/line/dto/CreateLineResponse.java
  src/main/java/com/knud4/an/line/dto/LineDTO.java
  src/main/java/com/knud4/an/line/dto/LineListDTO.java
Labels: documentation, enhancement

#45 Feat/issue 3/community entity
  src/main/java/com/knud4/an/community/entity/Category.java
  src/main/java/com/knud4/an/community/entity/Community.java
  src/main/java/com/knud4/an/community/repository/CommunityRepository.java
Labels: documentation, enhancement

#48 Feat: Community와 Comment 간 연관관계 추가
  src/main/java/com/knud4/an/comment/entity/Comment.java
  src/main/java/com/knud4/an/comment/repository/CommentRepository.java
  src/main/java/com/knud4/an/community/entity/Community.java
  src/main/java/com/knud4/an/community/repository/CommunityRepository.java
Labels: documentation, enhancement

#51 Feat: Board, Comment에 Profile과의 연관관계 추가
  src/main/java/com/knud4/an/board/Board.java
  src/main/java/com/knud4/an/comment/entity/Comment.java
Labels: documentation, enhancement

#53 Feat: Board, Comment, Community, Notice 클래스에 생성자 추가
  src/main/java/com/knud4/an/board/Board.java
  src/main/java/com/knud4/an/comment/entity/Comment.java
  src/main/java/com/knud4/an/community/entity/Community.java
  src/main/java/com/knud4/an/notice/entity/Notice.java
Labels: documentation, enhancement

#43 Feat: Account Controller 추가
  src/main/java/com/knud4/an/account/controller/AccountController.java
  src/main/java/com/knud4/an/account/dto/ProfileDTO.java
  src/main/java/com/knud4/an/account/dto/ProfileListResponse.java
Labels: documentation, enhancement

#56 Https 추가에 따른 쿠키, config 로직 일부 수정 / Interceptor 이슈 해결
  src/main/java/com/knud4/an/auth/controller/AuthController.java
  src/main/java/com/knud4/an/config/SecurityConfigure.java
  src/main/java/com/knud4/an/config/WebConfig.java
  src/main/java/com/knud4/an/exception/handler/JwtAccessDeniedHandler.java
  src/main/java/com/knud4/an/exception/handler/JwtNotAuthenticatedHandler.java
  src/main/java/com/knud4/an/interceptor/AccountTokenInterceptor.java
  src/main/java/com/knud4/an/interceptor/ProfileTokenInterceptor.java
  src/main/java/com/knud4/an/utils/cookie/CookieUtil.java
Labels: documentation, enhancement

#59 Feat: Report Entity 추가, 변경사항 반영
  src/main/java/com/knud4/an/comment/entity/Comment.java
  src/main/java/com/knud4/an/comment/entity/CommunityComment.java
  src/main/java/com/knud4/an/comment/entity/ReportComment.java
  src/main/java/com/knud4/an/comment/repository/CommentRepository.java
  src/main/java/com/knud4/an/community/entity/Community.java
  src/main/java/com/knud4/an/report/entity/Report.java
Labels: documentation, enhancement

#63 Feat: Comment Repository 추가
  src/main/java/com/knud4/an/comment/repository/CommunityCommentRepository.java
  src/main/java/com/knud4/an/comment/repository/ReportCommentRepository.java
Labels: documentation, enhancement

#64 Refactor: Report 연관관계 수정, 편의 메소드 수정
  src/main/java/com/knud4/an/comment/entity/ReportComment.java
  src/main/java/com/knud4/an/report/entity/Report.java
Labels: documentation, enhancement

#67 Feat: Community Repository 테스트, 수정 및 Service 추가
  src/main/java/com/knud4/an/community/dto/CreateCommunityForm.java
  src/main/java/com/knud4/an/community/repository/CommunityRepository.java
  src/main/java/com/knud4/an/community/service/CommunityService.java
  src/test/java/com/knud4/an/repository/CommunityRepositoryTest.java
Labels: documentation, enhancement

#69 Feat: Redis 추가
  build.gradle
  src/main/java/com/knud4/an/AnApplication.java
  src/main/java/com/knud4/an/config/RedisConfig.java
  src/main/java/com/knud4/an/utils/redis/RedisUtil.java
Labels: documentation, enhancement

#70 Feat: smtp Service 추가
  build.gradle
  src/main/java/com/knud4/an/smtp/service/AuthMailService.java
Labels: documentation, enhancement

#75 Feat: Notice DTO, Controller 추가
  src/main/java/com/knud4/an/notice/controller/NoticeController.java
  src/main/java/com/knud4/an/notice/dto/NoticeDTO.java
  src/main/java/com/knud4/an/notice/service/NoticeService.java
Labels: documentation, enhancement

#74 Feat: AuthMailController 추가 + Auth 메일 인증 기능 추가
  src/main/java/com/knud4/an/auth/controller/AuthController.java
  src/main/java/com/knud4/an/auth/service/AuthService.java
  src/main/java/com/knud4/an/smtp/controller/AuthMailController.java
  src/main/java/com/knud4/an/smtp/service/AuthMailService.java
Labels: documentation, enhancement

#79 Feat: CommunityComment, ReportComment Service 추가
  src/main/java/com/knud4/an/comment/dto/CreateCommentForm.java
  src/main/java/com/knud4/an/comment/repository/CommunityCommentRepository.java
  src/main/java/com/knud4/an/comment/repository/ReportCommentRepository.java
  src/main/java/com/knud4/an/comment/service/CommunityCommentService.java
  src/main/java/com/knud4/an/comment/service/ReportCommentService.java
Labels: documentation, enhancement

#82 Feat: Community DTO, Controller 추가
  src/main/java/com/knud4/an/community/controller/CommunityController.java
  src/main/java/com/knud4/an/community/dto/CommunityDTO.java
  src/main/java/com/knud4/an/community/service/CommunityService.java
Labels: documentation, enhancement

#83 Feat: Comment Controller, DTO 추가
  src/main/java/com/knud4/an/comment/controller/CommentController.java
  src/main/java/com/knud4/an/comment/dto/CommentDTO.java
Labels: documentation, enhancement

#84 Refactor: 토큰 정책 변경, refresh Token 추가
  src/main/java/com/knud4/an/auth/controller/AuthController.java
  src/main/java/com/knud4/an/auth/dto/TokenDTO.java
  src/main/java/com/knud4/an/auth/dto/account/SignInAccountResponse.java
  src/main/java/com/knud4/an/auth/dto/profile/SignInProfileResponse.java
  src/main/java/com/knud4/an/security/provider/JwtProvider.java
  src/main/java/com/knud4/an/utils/cookie/CookieUtil.java
Labels: documentation, enhancement

#86 Refactor: api 경로 변경
  src/main/java/com/knud4/an/account/controller/AccountController.java
  src/main/java/com/knud4/an/auth/controller/AuthController.java
  src/main/java/com/knud4/an/auth/dto/codeVerificationDTO.java
  src/main/java/com/knud4/an/config/SecurityConfigure.java
  src/main/java/com/knud4/an/config/WebConfig.java
  src/main/java/com/knud4/an/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/knud4/an/house/controller/HouseController.java
  src/main/java/com/knud4/an/line/controller/LineController.java
  src/main/java/com/knud4/an/report/controller/ReportController.java
  src/main/java/com/knud4/an/smtp/controller/AuthMailController.java
Labels: documentation

#89 Fix: username 중복 생성 방지, 타 계정 간 profile 이름 중복 허용
  src/main/java/com/knud4/an/account/repository/AccountRepository.java
  src/main/java/com/knud4/an/auth/service/AuthService.java
Labels: Fix

#90 Feat: logger 추가
  build.gradle
  src/main/java/com/knud4/an/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/knud4/an/logger/LoggingFilter.java
  src/main/java/com/knud4/an/logger/RequestWrapper.java
  src/main/java/com/knud4/an/logger/ResponseWrapper.java
Labels: documentation, enhancement

#91 Refactor: api 경로 변경
  src/main/java/com/knud4/an/comment/controller/CommentController.java
  src/main/java/com/knud4/an/community/controller/CommunityController.java
  src/main/java/com/knud4/an/config/SecurityConfig.java
  src/main/java/com/knud4/an/config/WebConfig.java
  src/main/java/com/knud4/an/notice/controller/NoticeController.java
Labels: documentation

#94 Feat: community api 수정
  src/main/java/com/knud4/an/board/Board.java
  src/main/java/com/knud4/an/comment/repository/CommunityCommentRepository.java
  src/main/java/com/knud4/an/comment/repository/ReportCommentRepository.java
  src/main/java/com/knud4/an/community/controller/CommunityController.java
  src/main/java/com/knud4/an/community/dto/CommunityDTO.java
  src/main/java/com/knud4/an/community/entity/Category.java
  src/main/java/com/knud4/an/community/entity/Community.java
  src/main/java/com/knud4/an/community/repository/CommunityRepository.java
  src/main/java/com/knud4/an/community/service/CommunityService.java
  src/main/java/com/knud4/an/config/SecurityConfig.java
  src/main/java/com/knud4/an/config/WebConfig.java
  src/main/java/com/knud4/an/notice/controller/NoticeController.java
  src/main/java/com/knud4/an/notice/dto/NoticeDTO.java
  src/main/java/com/knud4/an/notice/entity/Notice.java
  src/main/java/com/knud4/an/notice/service/NoticeService.java
Labels: documentation, enhancement

#95 Refactor: Security 예외 응답 로직 수정, Logging Filter 위치 수정
  src/main/java/com/knud4/an/config/SecurityConfig.java
  src/main/java/com/knud4/an/exception/handler/JwtAccessDeniedHandler.java
  src/main/java/com/knud4/an/exception/handler/JwtNotAuthenticatedHandler.java
  src/main/java/com/knud4/an/logger/LoggingFilter.java
Labels: documentation

#97 계정/프로필 로그아웃 기능 추가, swagger configure 추가, Manager 접근 권한 수정
  src/main/java/com/knud4/an/auth/controller/AuthController.java
  src/main/java/com/knud4/an/config/SecurityConfig.java
  src/main/java/com/knud4/an/config/SwaggerConfig.java
Labels: documentation, enhancement

#99 Feat: CommunityListDTO 추가
  src/main/java/com/knud4/an/community/controller/CommunityController.java
  src/main/java/com/knud4/an/community/dto/CommunityListDTO.java
  src/main/java/com/knud4/an/community/repository/CommunityRepository.java
  src/main/java/com/knud4/an/community/service/CommunityService.java
Labels: documentation, enhancement

#101 Feat: Comment 삭제 기능 추가
  src/main/java/com/knud4/an/comment/controller/CommentController.java
  src/main/java/com/knud4/an/comment/repository/CommunityCommentRepository.java
  src/main/java/com/knud4/an/comment/repository/ReportCommentRepository.java
  src/main/java/com/knud4/an/comment/service/CommunityCommentService.java
  src/main/java/com/knud4/an/comment/service/ReportCommentService.java
Labels: documentation, enhancement

#103 Feat: Community 수정, 삭제 추가
  src/main/java/com/knud4/an/board/Board.java
  src/main/java/com/knud4/an/comment/service/CommunityCommentService.java
  src/main/java/com/knud4/an/community/controller/CommunityController.java
  src/main/java/com/knud4/an/community/dto/CommunityDTO.java
  src/main/java/com/knud4/an/community/entity/Community.java
  src/main/java/com/knud4/an/community/repository/CommunityRepository.java
  src/main/java/com/knud4/an/community/service/CommunityService.java
  src/main/java/com/knud4/an/config/SecurityConfig.java
  src/main/java/com/knud4/an/config/WebConfig.java
Labels: documentation, enhancement

#102 Feat: WebSocket, Stomp 추가
  build.gradle
  src/main/java/com/knud4/an/config/StompWebSocketConfig.java
  src/main/java/com/knud4/an/logger/LoggingFilter.java
  src/main/java/com/knud4/an/security/provider/JwtProvider.java
  src/main/java/com/knud4/an/websocket/controller/AlertController.java
  src/main/java/com/knud4/an/websocket/dto/MessageDTO.java
  src/main/java/com/knud4/an/websocket/handler/StompErrorHandler.java
  src/main/java/com/knud4/an/websocket/interceptor/StompInboundInterceptor.java
Labels: documentation, enhancement
